### ISSUE TITLE
Python version lower than 3.10 not supported ? 

### ISSUE THREAD

**Issue by andremfreitas** [JosephBARBIERDARNAL/pypalettes#18]
Hi,

I wanted to start using pypalettes but quickly ran into a problem when import the library;

``` TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'``` 

This kind of syntax is only supported on 3.10 or later.
So I was wondering whether you're planning to support 3.10 or lower versions.

Thanks and good work,
Andre

**Comment by JosephBARBIERDARNAL** [comment]
Hi @andremfreitas ! thanks for this

That's a good question. I just made a quick PR #19  since it seems an easy fix.

Can you try the following and tell me how it goes? (it will the install the lastest version of pypalettes with the fix I just did)

```bash
pip uninstall pypalettes
pip install git+https://github.com/JosephBARBIERDARNAL/pypalettes.git
```

**Comment by JosephBARBIERDARNAL** [comment]
I've made a few changes since then and now pypalettes works with Python 3.9 and above ! I hope this meets your needs

**Comment by andremfreitas** [comment]
Awesome, thanks!
